apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporteer
  labels:
    app: reporteer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reporteer
  template:
    metadata:
      labels:
        app: reporteer
      annotations:
        io.katacontainers.config.hypervisor.kernel_params: " agent.guest_components_rest_api=all"
        io.containerd.cri.runtime-handler: kata-qemu-snp

    spec:
      runtimeClassName: kata-qemu-snp
      containers:
      - name: reporteer
        image: switchboardlabs/reporteer:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: SEV_SNP_CACHE_PATH
          value: "/tmp/certs"
        - name: REPORTEER_SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: reporteer-config
              key: server_port
        - name: REPORTEER_ENDPOINT_URL
          valueFrom:
            configMapKeyRef:
              name: reporteer-config
              key: endpoint_url
        - name: REPORTEER_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: reporteer-config
              key: log_level
        - name: VERIFY_AT_START
          valueFrom:
            configMapKeyRef:
              name: reporteer-config
              key: verify_at_start
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
---
apiVersion: v1
kind: Service
metadata:
  name: reporteer
spec:
  selector:
    app: reporteer
  ports:
  - port: 80
    targetPort: 3000
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: reporteer-config
data:
  server_port: "3000"
  endpoint_url: "http://127.0.0.1:8006/derived_key"
  log_level: "info"
  verify_at_start: "false"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oracle-landing-page
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - YOUR_HOST
    secretName: ingress-tls
  rules:
  - host: YOUR_HOST
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: reporteer
            port:
              number: 3000
